Script started on Thu 13 Sep 2018 05:34:53 PM EDT
[?1034hbash-4.2$ cd ~/os161/root
bash-4.2$ sys161 kernel
sys161: System/161 release 1.14, compiled Sep  4 2014 10:34:58

OS/161 base system version 1.11
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Moon Microsystems's system version 0 (ASST0 #3)

Cpu is MIPS r2000/r3000
336k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

Hello World
OS/161 kernel [? for menu]: p /sbin/poweroff
Operation took 0.000159280 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 327289882 cycles (4482060k, 18u, 322807804i)
sys161: 1982 irqs 6 exns 0r/0w disk 17r/696w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 13.082910 seconds (25.0166 mhz)
sys161: Elapsed virtual time: 13.091595280 seconds (25 mhz)
bash-4.2$ exit

Script done on Thu 13 Sep 2018 05:35:43 PM EDT
