Script started on Thu 13 Sep 2018 05:12:45 PM EDT
[?1034hbash-4.2$ cd ![K~/os161/root
bash-4.2$ st[Kys161 kernal
sys161: Cannot open boot image kernal: No such file or directory
bash-4.2$ sys161 kernal[1Plel
sys161: System/161 release 1.14, compiled Sep  4 2014 10:34:58

OS/161 base system version 1.11
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #2)

Cpu is MIPS r2000/r3000
336k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/poweroff 
Operation took 0.000159280 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 3905773475 cycles (26255978k, 18u, 3879517479i)
sys161: 16221 irqs 6 exns 0r/0w disk 18r/692w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 156.226927 seconds (25.0006 mhz)
sys161: Elapsed virtual time: 156.230939000 seconds (25 mhz)
bash-4.2$ exit

Script done on Thu 13 Sep 2018 05:16:11 PM EDT
